services:
  db:
    image: postgres:17.0
    container_name: postgres
    hostname: ${DB_HOST}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
